sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
- cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: NcdFEMS6dCBqinWgaNIQVg5A3ZUNwDXig4uRJXMRIWxX/2LuajUgR8r596udiuGDGkLXlAU6j2wJDrwB4MhqkKwOZh/ACykYa38K/dmdS9DGIV7AGrkAUpZfCFLmeEMf0f2hp/vCR/8S64hxx9wLAQKVqHJd2XsFzHCZul/gOChT0+TDDSKZiHLYxJuc9lgOs0uX5UiDSgberdLF6qYv/Fc5g+rzyGDxajHFQboRCg0reXZmx/y0eQ3x/O0wRZAkLFMNNKC/lx7ygJtlwE0MF3Vnc0ekD29QMoLbMIe7wOKFx5/ziFBthVhTWnSlUYM6Pn/FkZoIh1ckPG0e/3Bj8hvSkZwNbcsQCc8a0ZvljrSnKAQ3YjlmGdIBZoC1ilFI6PNkF0M5/xLdmWAQDt9pdEZjXyZGEn2D7I6MnFtkJQ9h0F9ZdcPjdF1Mj6FWYiNT/d8spDbBqKlfD/nKL82EPoQFJNEk/ekjfXIOAWGvTbDfCEtO9soT0JSZkq/L1ZfqA+k50RG8v31m7pdt+QXVH9409gnsMcEMALg/cEselmUWoct/uOgcaND13dCpwur9WHYy9ykMuGgJzPB5y5IVsqvkOQu3o46obqbhob7HO0VJi8FEh8O/vGhQXMO8Evnl81xUsc71B3o4gEpCpHU9cFUNjkDk49VUaa2mOdYw0MM=
  - secure: QvgxBra9+AjAPmEVrnq6rOrrt86qY8omX81jdtjx9b6brpFnOybozqWgnracjIoswCA70EvHSvUfick/5yKmWExmm0pwjxZMwJ20QalLHVmiKus8F7PCWjkEYjdR+G9zNSDuw7y2IkUoLKjGYHp7B4JQWl8fKeErGhqig40ipBYtZjQHz4pOtdJluLdWrRqrf342p6Nljz37VgDJYnHyxNSeE3jiA3oOqlZtrmr4v7B8ydZa07Rrvh4CfYkPIJyEE2x8+KypQepGROOP6S8NSerfVuJhrfyX/SDSVZ2ag+0fZ6NrQ5E5V2Zc66NMo8qrvowZVMhKmwOmoJA4JeUWRRLZ9XjhE5k9OJy4jTwh9eKyz800lonHcRM3Gc+mReVR9fVQng4jBTRR2vhgtSovVU4CNJzCn8V6ZxvKgBGOItBg02BJTtwyk82fGdaai0qlSXRP5ovFCx1zCrmTULKgt6FLqGM/ce4q+RaESqX2BZmZl7LAkDaZfR0oVCMGdX73TdZPSlfXvhVJDj7BZZRT1sAb146/r/0tUFsZuos8vAuickipUWZ8T5Hsul36kAozoFdKuWXpwnzZktvPhNHef0u7ZeI+uPilWfjFfRPQc93wfTRaBUjfXG5DsjesYvkxPUY1r/kyig9mV+loVoTooVISk1l4xl/Ih4fKGAl88jI=
